### ISSUE TITLE
"Disable Unused Features" could give bindgen as an example

### ISSUE THREAD

**Issue by lilianmoraru** [mre/mre.github.io#16]
https://endler.dev/2020/rust-compile-times/#disable-unused-features-of-crate-dependencies - "Disable Unused Features Of Crate Dependencies" could probably also give `bindgen` as an example for the `-sys` crates.
`bindgen` builds the CLI(with `clap` as a dependency) by default, most should probably disable the feature: https://github.com/stratis-storage/devicemapper-rs/pull/665/files
The suggestion is not evergreen though, since `bindgen` could easily disable the feature by default.

**Comment by mre** [comment]
Indeed! Great idea. I added a paragraph in https://github.com/mre/endler.dev/commit/0edbfe731d9da3077653c5b00d00b0fda656f2f8 and added a link to your Github profile for credit. Let me know if you'd like me to link elsewhere or make changes to the wording.
Thanks for the recommendation. ⭐

**Comment by lilianmoraru** [comment]
Thanks, that link(rust-rocksdb) is a more useful example

**Comment by mre** [comment]
Thank YOU for letting me know about the bindgen example. 🌹
