### ISSUE TITLE
I see you updated the minified file without also updating the unminified one for search.mjs

### ISSUE THREAD

**Issue by Jieiku** [mre/mre.github.io#22]
The minified file was updated Aug 21, 2021 https://github.com/mre/endler.dev/blob/master/static/search_min.js

The NOT minified file is still initial commit Sep 9, 2020: https://github.com/mre/endler.dev/blob/master/static/search.mjs

What steps need to be taken to convert search.mjs into search_min.js?

**Comment by mre** [comment]
Thanks for the hint. Big 🤦‍♂️.

> What steps need to be taken to convert search.mjs into search_min.js?

I forgot. 😆 It's been a while. Thought the CI pipeline would take care of it, but it doesn't.

**Comment by mre** [comment]
Actually:
https://github.com/mre/endler.dev/blob/0272ff2a5da6c9c3cacee5d2ec246ce3a236eeb3/Makefile#L46-L48

**Comment by mre** [comment]
So to answer your original question, we'd have to fix https://github.com/mre/endler.dev/pull/21 in order to resolve the issue. Need to fix the cavif installation which was the last thing I did before I ran out of time / got distracted. You can give it a shot if you like. 😊

**Comment by Jieiku** [comment]
I ended up rewriting the top half of the javascript for tinysearch, no idea if it will cause issues later with a newer version of tiny search. I have a couple more questions but they will be posted to the tinysearch repo after I do a bit of cleanup and setup an example site.

I really have never used mjs before, but I have things working well enough for my purposes at the moment.

**Comment by mre** [comment]
#21 is also resolved now. Guess we can close this.
(FYI: in case you're wondering why the timestamp for the non-minified file is still Sep 9, 2020, it's because the file hasn't changed since then and doesn't get auto-generated. However the search index is up-to-date again.)
Thanks for the report. 👍
