### ISSUE TITLE
Suggestion for compile times article: set opt-level=3 in profile.dev.build-override

### ISSUE THREAD

**Issue by jfmontanaro** [mre/mre.github.io#53]
Hi Matthias! I just came across your article on improving compile times in Rust, and, well, you did ask for suggestions 😁 

I can't remember where I originally saw this, but if you add this to your `Cargo.toml`:
```
[profile.dev.build-override]
opt-level = 3
```
It will force build-scripts and proc-macros to compile with opt-level=3 instead of the default (which is no optimizations, I believe.) 

This came make quite a difference for projects that use a lot of proc macros. E.g. in a [tauri](https://tauri.app) app that I'm working on, it dropped my hot build time from ~16s to ~6s. This is especially nice given that the Tauri tooling automatically triggers a rebuild every time you save one of your source files, so it happens a lot.

Obviously this will slow down cold builds, but only when building with the dev profile. IMO it's a worthwhile tradeoff.

**Comment by mre** [comment]
Hey @jfmontanaro,
thanks for the feedback.
According to https://doc.rust-lang.org/cargo/reference/profiles.html, `opt-level = 3` means "enable all optimizations" so I don't see how it could reduce compile times. Have you tried `opt-level = 0` (no optimizations) for comparison?

**Comment by jfmontanaro** [comment]
`opt-level = 0` for this specific sub-profile is actually the default, in both dev and release mode, according to [the same page](https://doc.rust-lang.org/cargo/reference/profiles.html#build-dependencies).

I think the reason it helps with build times is because it only applies to build scripts and proc-macros. Build scripts and proc-macros are unique because during a normal build, they are not only compiled but also executed (and in the case of proc-macros, they can be executed repeatedly). When your project uses a lot of proc-macros, optimizing the macros themselves can in theory save a lot of time.

That said, after writing all this up I went to test the performance difference again and found that it doesn't seem to match what I observed yesterday. I was also experimenting with different linkers yesterday, so it's possible that I confused the performance uplift from using a faster linker with that from using optimized proc-macros.

So I guess the difference isn't as dramatic as I thought. I think it can still be useful, but you have to either be using some _very_ complex proc-macros, or just invoke them a _lot_ for the difference to really show up.

BTW I did find where I originally saw this advice, it's in the [sqlx readme](https://github.com/launchbadge/sqlx) (down near the bottom). They only advise enabling optimizations specifically for the `sqlx-macros` crate, which is probably a better idea if you know what specific crate holds the macros that are slowing you down.

**Comment by mre** [comment]
Thanks for providing more details. Makes sense to me. I've added it into the proc-macro-tips section: https://github.com/mre/endler.dev/commit/66ed762f0dd24946b3db432715bc4afb6634d96b and quoted your explanation with reference to the source.

**Comment by mre** [comment]
Oh and if you have any more tips, please keep 'em coming. 👍
